pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      comment: 
        message: "Test test 🦄"
      assign:
        add_users:
          - "{{approved_reviews_by}}"