pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
        comment:
            message: "This pull request is now in conflict! @{{ author }} can you fix it? 🙏"
